version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - yarn run build
    finally:
      - echo 'This is the finally block executio!!!!!!!!!!!!!n!'
artifacts:
  files:
    - "**/*"
  base-directory: "build"
  discard-paths: yes
