version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  #pre_build:
  #@@@@@@@@@@@@@  commands:
  #######    - npm install
  build:
    commands:
      - npm run build
    finally:
      - echo 'This is the finally block execution!'
  post_build:
    - aws s3 cp dist/build/* s3://myweb-server1 --recursive
    - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
  discard-paths: yes
